name: Build and test the components of the system
run-name: Build and test the components of the system
on: [push]
jobs:
  song-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - run: cd capsule
      - run: go test ./...